/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-03-09 10:11:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles1.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 String ctxPath = request.getContextPath(); 
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\tth {\r\n");
      out.write("\t\tfont-family: \"제주고딕\";\r\n");
      out.write("\t\tfont-size: 15pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea, input[type=text] {\r\n");
      out.write("\t\tfont-family: \"제주고딕\";\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   table, th, td, input, textarea {border: solid gray 1px;}\r\n");
      out.write("   \r\n");
      out.write("   #table {border-collapse: collapse;\r\n");
      out.write("           width: 98%;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("   #table th, #table td{padding: 5px;}\r\n");
      out.write("   #table th{width: 10%; background-color: #DDDDDD; text-align: center;}\r\n");
      out.write("   #table td{width: 80%;}\r\n");
      out.write("   .long {width: 470px;}\r\n");
      out.write("   .short {width: 120px;}\r\n");
      out.write("   \r\n");
      out.write("   span#error {\r\n");
      out.write("   \tdisplay: none;\r\n");
      out.write("   \tcolor: red;\r\n");
      out.write("   }\r\n");
      out.write("\t\r\n");
      out.write("\tinput#name {\r\n");
      out.write("\t\twidth: 80px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput#subject {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tresize: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#btn {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\tjustify-content : center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbutton {\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t\tmargin-right: 20px;\r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tul {\r\n");
      out.write("\t  \tpadding-inline-start: 20px;\r\n");
      out.write("\t  \tmargin-bottom: 0px;\r\n");
      out.write("\t  \tborder: 1px; \r\n");
      out.write("\t  }\r\n");
      out.write("\t\t\r\n");
      out.write("</style>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar n = 0; // alert 한번만 뜨도록 설정\r\n");
      out.write("\tvar a = 0; // 조건 변수\r\n");
      out.write("\t// var content =\"\";\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("\t   \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"button#addfile\").on('click', function () {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t   alert(\"야호\");\r\n");
      out.write("\t\t   $(\"div#fileContainer\").append(\"<input type='file' name='file'>\")\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t});\r\n");
      out.write("\t   \r\n");
      out.write("  \t\t$('textarea#content').bind({\r\n");
      out.write("\t\t\tinput : textarea_analysis,\r\n");
      out.write("\t\t\tpaste : textarea_analysis,\r\n");
      out.write("\t\t\tpropertychange : textarea_analysis\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input#subject').bind({\r\n");
      out.write("\t\t\tinput : subject_analysis,\r\n");
      out.write("\t\t\tpaste : subject_analysis,\r\n");
      out.write("\t\t\tpropertychange : subject_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input#name').bind({\r\n");
      out.write("\t\t\tinput : name_analysis,\r\n");
      out.write("\t\t\tpaste : name_analysis,\r\n");
      out.write("\t\t\tpropertychange : name_analysis\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\t    \r\n");
      out.write(" \t\t$('input#file').bind({\r\n");
      out.write("\t\t\tinput : file_analysis\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t   // 쓰기버튼\r\n");
      out.write("\t\t   $(\"button#btnWrite\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t   var nameVal = $(\"input#name\").val(); \r\n");
      out.write("\t\t\t   if(nameVal == \"\") {\r\n");
      out.write("\t\t\t\t   alert(\"작성자명을 입력하세요\");\r\n");
      out.write("\t\t\t\t   $(\"input#name\").focus();\r\n");
      out.write("\t\t\t\t   return;\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t    // 글제목 유효성 검사\r\n");
      out.write("\t\t\t\tvar subjectVal = $(\"input#subject\").val().trim();\r\n");
      out.write("\t\t\t\tif(subjectVal == \"\") {\r\n");
      out.write("\t\t\t\t\talert(\"글제목을 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t$(\"input#subject\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t    // 글내용 유효성 검사\r\n");
      out.write("\t\t\t\tvar contentVal = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t\t\tif(contentVal == \"\") {\r\n");
      out.write("\t\t\t\t\talert(\"글내용을 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t$(\"textarea#content\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t        $(\"textarea#content\").val(contentVal);\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t\t// 글암호 유효성 검사\r\n");
      out.write("\t\t\t\tvar pwVal = $(\"input#pw\").val().trim();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(pwVal == \"\") {\r\n");
      out.write("\t\t\t\t\talert(\"글암호를 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t$(\"input#pw\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar regExp = new RegExp(/^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g);\r\n");
      out.write("\t\t\t\t\tvar bool = regExp.test(pwVal);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(!bool) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 암호가 정규표현식에 위배된 경우\r\n");
      out.write("\t\t\t\t\t\talert(\"암호는 영문자,숫자,특수기호가 혼합된 8~15 글자로 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t   \t$(\"span.error\").show();\r\n");
      out.write("\t\t\t\t\t   \t$(\"input#pw\").focus();\t\t\t\t\t   \t\r\n");
      out.write("\t\t\t\t\t    return;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 폼(form) 을 전송(submit)\r\n");
      out.write("\t\t\t\tvar frm = document.addFrm;\r\n");
      out.write("\t\t\t\tfrm.method = \"POST\";\r\n");
      out.write("\t\t\t\tfrm.action = \"");
      out.print( ctxPath);
      out.write("/addEnd.action\";\r\n");
      out.write("\t\t\t\tfrm.submit();  \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t}); // end of $(document).ready(function(){\r\n");
      out.write("\t\t   \r\n");
      out.write("\tfunction textarea_analysis(event) {\r\n");
      out.write("\t\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t\t//alert(\"분석함수가 실행되었습니다.\");\r\n");
      out.write("\t\t    content = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t    $(\"td#result\").html(\"(\"+content.length+\" / 최대 4500자)\");\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    if(content.length > 4500 ) {\r\n");
      out.write("\t\t    \ttextarea_unbind();\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t        alert_content(1);\r\n");
      out.write("\t\t\t\t$(\"textarea#content\").val(content.substring(0, 4500));\r\n");
      out.write("\t\t\t\tcontent = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t\t\t$(\"td#result\").html(\"(4500 / 최대 4500자)\");\r\n");
      out.write("\t\t\t\treturn;\t\t\t\t\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\treturn; \r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction textarea_bind() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar content=$(\"textarea#content\").val();\r\n");
      out.write("\t\t$(\"textarea#content\").val(content.substring(0, 4500));\r\n");
      out.write("\t\t$('textarea#content').bind({\r\n");
      out.write("\t\t\tpaste : textarea_analysis,\r\n");
      out.write("\t\t\tinput : textarea_analysis,\r\n");
      out.write("\t\t\tpropertychange : textarea_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction textarea_unbind() {\r\n");
      out.write("\r\n");
      out.write("\t\t//alert(\"unbind 함수가 실행되었습니다.\");\r\n");
      out.write("\t\t$(\"textarea#content\").unbind(\"input\");\r\n");
      out.write("\t\t$(\"textarea#content\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"textarea#content\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction subject_analysis(event) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar subject = $(\"input#subject\").val()\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (subject.length > 75) {\r\n");
      out.write("\t\t\tsubject = $(this).val().trim();\r\n");
      out.write("\t\t\tsubject_unbind();\r\n");
      out.write("\t\t\talert_content(2);\r\n");
      out.write("\t\t\t$(this).val(subject.substring(0, 75));\r\n");
      out.write("\t\t\t$(\"input#subject\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction subject_bind() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// alert(\"제목 bind 함수를 실행합니다.\");\r\n");
      out.write("\t\tvar subject = $(\"input#subject\").val();\r\n");
      out.write("\t\t$(\"input#subject\").val(subject.substring(0, 75));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input#subject').bind({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpaste : subject_analysis,\r\n");
      out.write("\t\t\tinput : subject_analysis,\r\n");
      out.write("\t\t\tpropertychange : subject_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction subject_unbind() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"input#subject\").unbind(\"input\");\r\n");
      out.write("\t\t$(\"input#subject\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"input#subject\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction name_analysis(event) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tname = $(\"input#name\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (name.length > 5) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tname = $(this).val().trim();\r\n");
      out.write("\t\t\tname_unbind();\r\n");
      out.write("\t\t\talert_content(3);\r\n");
      out.write("\t\t\t$(this).val(name.substring(0, 5));\r\n");
      out.write("\t\t\t$(\"input#name\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction name_bind() {\r\n");
      out.write("\t\tvar name = $(\"input#name\").val();\r\n");
      out.write("\t\t$(\"input#name\").val(name.substring(0, 5));\r\n");
      out.write("\t\t$('input#name').bind({\r\n");
      out.write("\t\t\tpaste : name_analysis,\r\n");
      out.write("\t\t\tinput : name_analysis,\r\n");
      out.write("\t\t\tpropertychange : name_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction name_unbind() {\r\n");
      out.write("\r\n");
      out.write("\t\t//alert(\"unbind 함수가 실행되었습니다.\");\r\n");
      out.write("\t\t$(\"input#name\").unbind(\"input\");\r\n");
      out.write("\t\t//$(\"input#name\").unbind(\"change\");\r\n");
      out.write("\t\t$(\"input#name\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"input#name\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction alert_content(a) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 함수 실행 깃발\r\n");
      out.write("\r\n");
      out.write("\t\tif (n == 1) {\r\n");
      out.write("\t\t\tn = 0;\r\n");
      out.write("\t\t\ttextarea_bind();\r\n");
      out.write("\t\t\tsubject_bind();\r\n");
      out.write("\t\t\tname_bind();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 내용\r\n");
      out.write("\t\tif (a == 1) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"내용은 최대 4500자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t  alert_content(1);\r\n");
      out.write("\t\t\t}, 0.01);  \r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 제목\r\n");
      out.write("\t\tif (a == 2) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"제목은 최대 75자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\talert_content(2);\t\t\r\n");
      out.write("\t\t\t\t}, 0.01);\r\n");
      out.write("\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t\t// 이름\r\n");
      out.write("\t\tif (a == 3) {\r\n");
      out.write("\t\t\talert(\"이름은 최대 5자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\talert_content(3);\t\t\r\n");
      out.write("\t\t\t\t}, 0.01);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\r\n");
      out.write("\t}; // end of alert 함수\r\n");
      out.write("\t\r\n");
      out.write("\tfunction file_analysis() {\r\n");
      out.write("\t\t\r\n");
      out.write("        var fileInput = document.getElementById(\"file\");\r\n");
      out.write("        var files = fileInput.files;\r\n");
      out.write("        var file;\r\n");
      out.write("         \r\n");
      out.write("        var html=\"\";\r\n");
      out.write("        \r\n");
      out.write("        if(files.length > 5) {\r\n");
      out.write("        \talert(\"파일 갯수는 최대 5개까지 첨부 가능합니다.\");\r\n");
      out.write("        \t$(\"input#file\").val(\"\");\r\n");
      out.write("        \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("            $(\"strong#totalSize\").html(\"( 0MB / 20MB )\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        var totalFileSize = 0;\r\n");
      out.write("        \r\n");
      out.write("        for (var i = 0; i < files.length; i++) {\r\n");
      out.write("             \r\n");
      out.write("            file = files[i];\r\n");
      out.write("            \r\n");
      out.write("            console.log(file);\r\n");
      out.write("            var maxSize = 20 * 1024 * 1024; // 20MB\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            totalFileSize+=file.size;\r\n");
      out.write("\t\t\t            \r\n");
      out.write("            // 크기 체크 \r\n");
      out.write("             if(totalFileSize > maxSize) {\r\n");
      out.write("            \talert(\"최대 20MB까지 사용이 가능합니다.\");\r\n");
      out.write("            \t$(\"input#file\").val(\"\");\r\n");
      out.write("            \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("                $(\"strong#totalSize\").html(\"( 0MB / 20MB )\");\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            // 파일 확장자 체크 \r\n");
      out.write("            var IMG_FORMAT = \"\\\\.(bmp|gif|jpg|jpeg|png)$\";\r\n");
      out.write("\r\n");
      out.write("             if( (new RegExp(IMG_FORMAT, \"i\")).test(file.name) ) {\r\n");
      out.write("            \thtml+=\"<li>\"+file.name+\" (\"+file.size+\" Byte) </li>\";\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("             \r\n");
      out.write("            else {\r\n");
      out.write("            \talert(\"bmp, gif, jpg, jpeg, png 파일만 첨부하실 수 있습니다.\");\r\n");
      out.write("            \t$(\"input#file\").val(\"\");\r\n");
      out.write("            \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("                $(\"strong#totalSize\").html(\"( 0MB / 20MB )\");\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("             \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        var totalSize = (totalFileSize/(1024*1024)).toFixed(2);\r\n");
      out.write("        \r\n");
      out.write("        $(\"ul#fileList\").html(html);\r\n");
      out.write("        \r\n");
      out.write("        $(\"strong#totalSize\").html(\"( \"+totalSize+\"MB / 20MB )\");\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delFile() {\r\n");
      out.write("\t\t\r\n");
      out.write("       \t$(\"input#file\").val(\"\");\r\n");
      out.write("    \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("        $(\"strong#totalSize\").html(\"( 0MB / 20MB )\");\r\n");
      out.write("\t}; \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"padding-left: 5%;\">\r\n");
      out.write(" <h1>글쓰기</h1>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" <form name=\"addFrm\" enctype=\"multipart/form-data\"> \r\n");
      out.write("      <table summary=\"글을 작성할 수 있도록 만든 표\" id=\"table\">\r\n");
      out.write("      <caption>글쓰기 표</caption>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th scope=\"row\"> <label for=\"name\">작성자  </label> </th>\r\n");
      out.write("\t            <td>\r\n");
      out.write("                <input type=\"hidden\" name=\"fk_userid\" value=\"leess\" />\r\n");
      out.write("                <input type=\"text\" name=\"name\" id=\"name\" value=\"\" class=\"name\" title=\"작성자의 이름을 입력하세요\"  maxlength='10'/>       \r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th scope=\"row\"><label for=\"subject\">제목 </label></th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"text\" name=\"subject\" id=\"subject\" class=\"long\" maxlength='210'  title=\"글 제목 입력하세요\" />       \r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th scope=\"row\"><label for=\"content\">내용 </label></th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <textarea rows=\"10\" cols=\"100\" style=\"height: 612px;\" name=\"content\" id=\"content\" title=\"글 내용을 입력하세요\" ></textarea>\r\n");
      out.write("                <span id=\"result\"></span>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th scope=\"row\">글자 수</th>\r\n");
      out.write("            <td id=\"result\">\r\n");
      out.write("           </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("         <!-- <input multiple=\"multiple\" type=\"file\" name=\"attach\" id=\"file\"/> -->\r\n");
      out.write("\t\t          \r\n");
      out.write("         <!-- <div id=\"fileContainer\">\r\n");
      out.write("\t\t          \r\n");
      out.write("         <input type=\"file\" name=\"attach\"> \r\n");
      out.write("          \t</div>\r\n");
      out.write("          \t\r\n");
      out.write("         <button type=\"button\" id=\"addfile\">파일추가</button> -->\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th scope=\"row\"> <label for=\"file\">파일첨부</label></th>\r\n");
      out.write("            <td>\r\n");
      out.write("\t            <input multiple=\"multiple\" type=\"file\" name=\"attach\" id=\"file\" title=\"파일 선택하기\" /> <button type=\"button\" title=\"파일 삭제하기\" style=\"display: inline;\" onclick=\"delFile();\">파일 삭제</button>\r\n");
      out.write("\t            <div >\r\n");
      out.write("\t            \t<ul id=\"fileList\" style=\"filename\"></ul>\r\n");
      out.write("\t            </div> \r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("         \t<th scope=\"row\"><label for=\"totalSize\">파일크기</label></th>\r\n");
      out.write("         \t<td>\r\n");
      out.write("\t\t\t\t<strong id=\"totalSize\"></strong>\t\t\t\r\n");
      out.write("         \t</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th scope=\"row\"><label for=\"pw\">글암호</label></th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"password\" name=\"pw\" id=\"pw\" title=\"글 암호 입력\"  class=\"short\"/> \r\n");
      out.write("               <span id=\"error\" class=\"error\">암호는 영문자,숫자,특수기호가 혼합된 8~15 글자로 입력하세요.</span>      \r\n");
      out.write("            </td>\r\n");
      out.write("            \r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\t  \r\n");
      out.write("\t         \r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <input type=\"hidden\" name=\"fk_seq\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.fk_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      <input type=\"hidden\" name=\"groupno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.groupno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      <input type=\"hidden\" name=\"depthno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.depthno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      <div id=\"btn\">\r\n");
      out.write("\t      <div>\r\n");
      out.write("\t     \t<button type=\"button\" id=\"btnWrite\">쓰기</button>\r\n");
      out.write("         \t<button type=\"button\" onclick=\"javascript:history.back()\">취소</button> \r\n");
      out.write("\t      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </form>\r\n");
      out.write("   \r\n");
      out.write("</div>    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
