/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-03-09 09:07:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles1.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/cjh20/OneDrive/Desktop/NCS%20(1)/bowtech/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612221392006L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String ctxPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("th {\r\n");
      out.write("\tfont-family: \"제주고딕\";\r\n");
      out.write("\tfont-size: 15pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea, input[type=text] {\r\n");
      out.write("\tfont-family: \"제주고딕\";\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table, th, td, input, textarea {\r\n");
      out.write("\tborder: solid gray 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\twidth: 98%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table th, #table td {\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table th {\r\n");
      out.write("\twidth: 10%;\r\n");
      out.write("\tbackground-color: #DDDDDD;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table td {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".long {\r\n");
      out.write("\twidth: 470px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".short {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span#error {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input#subject {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tresize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#btn {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#lost {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar n = 1; // alert 한번만 뜨도록 설정\r\n");
      out.write("\tvar a = 0; // 조건 변수\r\n");
      out.write("\r\n");
      out.write("\tvar checkpwVal = 0; // 암효 맞는지 틀렸는지 여부\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar indexNumberArray= new Array();\r\n");
      out.write("\tvar totalFileSize = 0;\r\n");
      out.write("\tvar total='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar lo=(total/(1024*1024)).toFixed(2);\r\n");
      out.write("        $(\"strong#totalSize\").html(\"( \"+lo+\"MB / 20MB )\");\r\n");
      out.write("        \r\n");
      out.write("\t\ttextarea_analysis();\r\n");
      out.write("\t\t\r\n");
      out.write("/*         indexNumberArray.push(i);\r\n");
      out.write("        var index=3;\r\n");
      out.write("        indexNumber+=index+\",\";\r\n");
      out.write("        indexNumber+=1+\",\";\r\n");
      out.write("        alert(indexNumber); */\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write(" \t\t$('input#file').bind({\r\n");
      out.write("\t\t\tinput : file_analysis\r\n");
      out.write("\t\t}); \r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('textarea#content').bind({\r\n");
      out.write("\t\t\tinput : textarea_analysis,\r\n");
      out.write("\t\t\t//change : textarea_analysis,\r\n");
      out.write("\t\t\tpaste : textarea_analysis,\r\n");
      out.write("\t\t\tpropertychange : textarea_analysis\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input#subject').bind({\r\n");
      out.write("\t\t\tinput : subject_analysis,\r\n");
      out.write("\t\t\t//change : subject_analysis,\r\n");
      out.write("\t\t\tpaste : subject_analysis,\r\n");
      out.write("\t\t\tpropertychange : subject_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 완료버튼\r\n");
      out.write("\t\t$(\"button#btnUpdate\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    // 글제목 유효성 검사\r\n");
      out.write("\t\t\t\t\tvar subjectVal = $(\"input#subject\").val().trim();\r\n");
      out.write("\t\t\t\t\tif(subjectVal == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"글 제목을 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    // 글내용 유효성 검사\r\n");
      out.write("\t\t\t\t\tvar contentVal = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t\t\t\tif(contentVal == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"글 내용을 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t\t$(\"textarea#content\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t        $(\"textarea#content\").val(contentVal);\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t\t\t// 글암호 유효성 검사\r\n");
      out.write("\t\t\t\t\tvar pwVal = $(\"input#pw\").val().trim();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(pwVal == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"글암호를 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t\t$(\"input#pw\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar regExp = new RegExp(/^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g);\r\n");
      out.write("\t\t\t\t\t\tvar bool = regExp.test(pwVal);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(!bool) {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t// 암호가 정규표현식에 위배된 경우\r\n");
      out.write("\t\t\t\t\t\t\talert(\"암호는 영문자,숫자,특수기호가 혼합된 8~15 글자로 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t\t    $(this).focus();\r\n");
      out.write("\t\t\t\t\t\t   \t$(\"span.error\").show();\r\n");
      out.write("\t\t\t\t\t\t    return;\r\n");
      out.write("\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcheckpw();\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 폼(form)을 전송(submit)\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}); // end of updateBtn Function\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}); // end of $(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction textarea_analysis(event) {\r\n");
      out.write("\t\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t\t//alert(\"분석함수가 실행되었습니다.\");\r\n");
      out.write("\t\t    content = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t    $(\"td#result\").html(\"(\"+content.length+\" / 최대 4500자)\");\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    if(content.length > 4500 ) {\r\n");
      out.write("\t\t    \ttextarea_unbind();\r\n");
      out.write("\t\t        alert_content(1);\r\n");
      out.write("\t\t\t\t$(\"textarea#content\").val(content.substring(0, 4500));\r\n");
      out.write("\t\t\t\tcontent = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t\t\t$(\"td#result\").html(\"(4500 / 최대 4500자)\");\r\n");
      out.write("\t\t\t\treturn;\t\t\t\t\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\treturn; \r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction textarea_bind() {\r\n");
      out.write("\t\tvar content=$(\"textarea#content\").val();\r\n");
      out.write("\t\t$(\"textarea#content\").val(content.substring(0, 4500));\r\n");
      out.write("\t\t$('textarea#content').bind({\r\n");
      out.write("\t\t\t//change : textarea_analysis,\r\n");
      out.write("\t\t\tpaste : textarea_analysis,\r\n");
      out.write("\t\t\tinput : textarea_analysis,\r\n");
      out.write("\t\t\tpropertychange : textarea_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction textarea_unbind() {\r\n");
      out.write("\r\n");
      out.write("\t\t//alert(\"unbind 함수가 실행되었습니다.\");\r\n");
      out.write("\t\t$(\"textarea#content\").unbind(\"input\");\r\n");
      out.write("\t\t//$(\"textarea#content\").unbind(\"change\");\r\n");
      out.write("\t\t$(\"textarea#content\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"textarea#content\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction subject_analysis(event) {\r\n");
      out.write("\r\n");
      out.write("\t\tsubject = $(\"input#subject\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (subject.length > 75) {\r\n");
      out.write("\t\t\tsubject = $(this).val().trim();\r\n");
      out.write("\t\t\tsubject_unbind();\r\n");
      out.write("\t\t\talert_content(2);\r\n");
      out.write("\t\t\t$(this).val(subject.substring(0, 75));\r\n");
      out.write("\t\t\t$(\"input#subject\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction subject_bind() {\r\n");
      out.write("\t\tvar subject=$(\"input#subject\").val();\r\n");
      out.write("\t\t$(\"input#subject\").val(subject.substring(0, 75));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input#subject').bind({\r\n");
      out.write("\t\t\tpaste : subject_analysis,\r\n");
      out.write("\t\t\tinput : subject_analysis,\r\n");
      out.write("\t\t\tpropertychange : subject_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction subject_unbind() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"input#subject\").unbind(\"input\");\r\n");
      out.write("\t\t$(\"input#subject\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"input#subject\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction alert_content(a) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 함수 실행 깃발\r\n");
      out.write("\r\n");
      out.write("\t\tif (n == 1) {\r\n");
      out.write("\t\t\tn = 0;\r\n");
      out.write("\t\t\ttextarea_bind();\r\n");
      out.write("\t\t\tsubject_bind();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 내용\r\n");
      out.write("\t\tif (a == 1) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"내용은 최대 4500자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\t  setTimeout(function() {\r\n");
      out.write("\t\t\t\t  alert_content(1);\r\n");
      out.write("\t\t\t}, 0.1);  \r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 제목\r\n");
      out.write("\t\tif (a == 2) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"제목은 최대 75자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\talert_content(2);\t\t\r\n");
      out.write("\t\t\t\t}, 0.1);\r\n");
      out.write("\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t\t// 이름\r\n");
      out.write("\t\tif (a == 3) {\r\n");
      out.write("\t\t\talert(\"이름은 최대 5자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\talert_content(3);\t\t\r\n");
      out.write("\t\t\t\t}, 0.1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\r\n");
      out.write("\t}; // end of alert 함수\r\n");
      out.write("\t\r\n");
      out.write("function checkpw() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("    \t\turl:\"");
      out.print(ctxPath);
      out.write("/checkpw.action\",\r\n");
      out.write("    \t\tdata:{\"seq\":");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("    \t\t\t  \"pw\":$(\"input#pw\").val()\t\r\n");
      out.write("    \t\t\t},  \r\n");
      out.write("    \t\ttype:\"post\",\r\n");
      out.write("    \t\tdataType:\"json\",    \r\n");
      out.write("    \t\tsuccess:function(json){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t\t\tvar count = json.n; \r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\tif(count == 0) {\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("       \t\t\t\talert(\"글 암호가 맞지 않습니다.\");\r\n");
      out.write("    \t\t\t\t$(\"input#pw\").focus();\r\n");
      out.write("    \t\t\t\treturn;\t\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\telse {\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\tvar indexString=indexNumberArray.join(\",\");\r\n");
      out.write("    \t\t\t\t$(\"input#indexString\").val(indexString);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\talert(indexString);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t    var frm = document.editFrm;\r\n");
      out.write("    \t\t\t\tfrm.method = \"POST\";\r\n");
      out.write("    \t\t\t\tfrm.action = \"");
      out.print( ctxPath);
      out.write("/editEnd.action\";\r\n");
      out.write("    \t\t\t\tfrm.submit(); \r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\treturn;\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\terror: function(request, status, error){\r\n");
      out.write("    \t\t\t alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}// end of function isExistEmailCheck()--------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("function file_analysis(number) {\r\n");
      out.write("\t\t\r\n");
      out.write("        var fileInput = document.getElementById(\"file\");\r\n");
      out.write("        var files = fileInput.files;\r\n");
      out.write("        var file;\r\n");
      out.write("         \r\n");
      out.write("        var html=\"\";\r\n");
      out.write("        \r\n");
      out.write("        // 파일크기만 별도로 호출하는게 편할듯.\r\n");
      out.write("        \r\n");
      out.write("        var orgFilenameList='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orgFilenameList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("        var fileSizeArray = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fileSizeArray}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("        \r\n");
      out.write("\t    var filesSize = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${filesSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t    var filesSizeArray=filesSize.split(\",\");\r\n");
      out.write("\t    \r\n");
      out.write("        var orginfiles=\"\";\r\n");
      out.write("        var oldFileCnt=$(\"ul#oldFileList>li\").length;\r\n");
      out.write("        var orgFilename ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orgFilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        if( files.length + oldFileCnt  > 5) {\r\n");
      out.write("        \talert(\"파일 갯수는 최대 5개까지 첨부 가능합니다.\");\r\n");
      out.write("        \t$(\"input#file\").val(\"\");\r\n");
      out.write("        \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("            $(\"strong#totalSize\").html(\"( \"+total+\"MB / 20MB )\");\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        for (var i = 0; i < files.length; i++) {\r\n");
      out.write("             \r\n");
      out.write("            file = files[i];\r\n");
      out.write("            \r\n");
      out.write("            console.log(file);\r\n");
      out.write("            var maxSize = 20 * 1024 * 1024; // 20MB\r\n");
      out.write("            \r\n");
      out.write("            totalFileSize+=file.size;\r\n");
      out.write("\t\t\t\t\t\t            \r\n");
      out.write("            // 크기 체크 \r\n");
      out.write("             if(totalFileSize+total > maxSize) {\r\n");
      out.write("            \talert(\"최대 20MB까지 사용이 가능합니다.\");\r\n");
      out.write("            \t$(\"input#file\").val(\"\");\r\n");
      out.write("            \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("                $(\"strong#totalSize\").html(\"( \"+total+\"MB / 20MB )\");\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            // 파일 확장자 체크 \r\n");
      out.write("            var IMG_FORMAT = \"\\\\.(bmp|gif|jpg|jpeg|png)$\";\r\n");
      out.write("\r\n");
      out.write("             if( (new RegExp(IMG_FORMAT, \"i\")).test(file.name) ) {\r\n");
      out.write("            \thtml+=\"<li>\"+file.name+\" (\"+file.size+\" Byte) </li>\";\r\n");
      out.write("            \t}\r\n");
      out.write("             \r\n");
      out.write("            else {\r\n");
      out.write("            \talert(\"bmp, gif, jpg, jpeg, png 파일만 첨부하실 수 있습니다.\");\r\n");
      out.write("            \t$(\"input#file\").val(\"\");\r\n");
      out.write("            \t$(\"ul#fileList\").html(\"\");\r\n");
      out.write("                $(\"strong#totalSize\").html(\"( \"+total+\"MB / 20MB )\");\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("        } // end of for \r\n");
      out.write("        \r\n");
      out.write("        \t\r\n");
      out.write("            // html 첨부가 안된다??\r\n");
      out.write("            \t\t\r\n");
      out.write("\t\t    // 기존파일을 다지우지 않았을 경고 추가파일이 있을경우 \r\n");
      out.write("\t\t\tif(Number(total) != 0 && files.length != 0) {\r\n");
      out.write("\t\t\t\ttotalFileSize+=total;\r\n");
      out.write("\t\t\t\tvar totalSize = (totalFileSize/(1024*1024)).toFixed(2);\r\n");
      out.write("\t\t        $(\"strong#totalSize\").html(\"( \"+totalSize+\"MB / 20MB )\");\r\n");
      out.write("\t\t        $(\"ul#newFileList\").html(html);\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        alert(\"기존파일을 다지우지 않았을 경고 추가파일이 있을경우\");\r\n");
      out.write("        \t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t// 파일도 다지우고 첨부파일도 없는 경우에\t\t\t\r\n");
      out.write("\t\t\tif(files.length == 0 && oldFileCnt == 0 ) {\r\n");
      out.write("\t\t\t\tvar totalSize = (totalFileSize/(1024*1024)).toFixed(2);\r\n");
      out.write("\t\t        $(\"strong#totalSize\").html(\"( 0MB / 20MB )\");\r\n");
      out.write("\t\t        $(\"ul#newFileList\").html(html);\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        alert(\"파일도 다지우고 첨부파일도 없는 경우에\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 기존파일 다 삭제하고 추가 했을 파일이 있을경우\t\t\r\n");
      out.write("\t\t\tif(files.length != 0 && oldFileCnt == 0 ) {\r\n");
      out.write("\t\t\t\tvar totalSize = (totalFileSize/(1024*1024)).toFixed(2);\r\n");
      out.write("\t\t        $(\"strong#totalSize\").html(\"( \"+totalSize+\"0MB / 20MB )\");\r\n");
      out.write("\t\t        $(\"ul#newFileList\").html(html);\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        alert(\"기존파일 다 삭제하고 추가 했을 파일이 있을경우\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("        \r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delFile() {\r\n");
      out.write("\t\t\r\n");
      out.write("       \t$(\"input#file\").val(\"\");\r\n");
      out.write("    \t$(\"ul#newFileList\").html(\"\");\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar lo=(total/(1024*1024)).toFixed(2);\r\n");
      out.write("        $(\"strong#totalSize\").html(\"( \"+lo+\"MB / 20MB )\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}; \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delOldFile(i) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"li\").remove(\"#file\"+i);\r\n");
      out.write("\t\tindexNumberArray.push(i);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar filesSize = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${filesSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t    var filesSizeArray=filesSize.split(\",\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    total=total-filesSizeArray[i];\r\n");
      out.write("\t    file_analysis();\r\n");
      out.write("\t\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"padding-left: 5%;\">\r\n");
      out.write("\r\n");
      out.write("\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/tiles1/board/edit.jsp(515,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<div id=\"lost\">\r\n");
            out.write("\t\t\t<h2>요청하신 페이지를 찾을 수 없습니다.</h2>\r\n");
            out.write("\t\t\t<h5>입력한 주소가 잘못되었거나, 사용이 일시 중단되어 요청하신 페이지를 찾을 수 없습니다.</h5>\r\n");
            out.write("\t\t\t<h5>서비스 이용에 불편을 드려 죄송합니다.</h5>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\r\n");
            out.write("\t\t<div id=\"btn\">\r\n");
            out.write("\t\t\t<div>\r\n");
            out.write("\t\t\t\t<button type=\"button\" title=\"게시판 메인으로 돌아가기\"\r\n");
            out.write("\t\t\t\t\tonclick=\"javascript:location.href='");
            out.print(request.getContextPath());
            out.write("/list.action'\">게시판\r\n");
            out.write("\t\t\t\t\t메인으로</button>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/tiles1/board/edit.jsp(531,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<h1>글수정</h1>\r\n");
          out.write("\r\n");
          out.write("\t\t<form name=\"editFrm\" enctype=\"multipart/form-data\">\r\n");
          out.write("\t\t\t<table summary=\"수정할 게시글의 내용을 담은 표 \"  id=\"table\">\r\n");
          out.write("\t\t\t<caption>수정할 게시글 표</caption>\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">작성자</th>\r\n");
          out.write("\t\t\t\t\t<td>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write(" <input\r\n");
          out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"seq\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" /> <input\r\n");
          out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"name\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" /></td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">작성일</th>\r\n");
          out.write("\t\t\t\t\t<td>");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t    <input type=\"hidden\" name=\"regDate\" id=\"regDate\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"long\" value=\"");
          if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\"\r\n");
          out.write("\t\t\t\t\t/></td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">제목</th>\r\n");
          out.write("\t\t\t\t\t<td><input type=\"text\" name=\"subject\" id=\"subject\" title=\"변경할 제목 입력\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"long\" value=\"");
          if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tmaxlength='200' /></td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">내용</th>\r\n");
          out.write("\t\t\t\t\t<td><textarea rows=\"10\"  title=\"변경할 내용 입력\" cols=\"100\" style=\"height: 612px;\"\r\n");
          out.write("\t\t\t\t\t\t\tname=\"content\" id=\"content\">");
          if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</textarea></td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">글자 수</th>\r\n");
          out.write("\t\t\t\t\t<td id=\"result\"></td>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write(" \t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">파일추가</th>\r\n");
          out.write("\t\t\t\t\t<td><input multiple=\"multiple\" type=\"file\" name=\"attach\" id=\"file\" />\r\n");
          out.write("\t\t\t\t\t\t<button title=\"파일 삭제 하기\" type=\"button\" style=\"display: inline;\"\r\n");
          out.write("\t\t\t\t\t\t\tonclick=\"delFile();\">파일 삭제</button>\r\n");
          out.write("\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t<ul id=\"newFileList\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">기존파일</th>\r\n");
          out.write("\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t<ul id=\"oldFileList\">\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"indexString\"id=\"indexString\"></input>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">파일크기</th>\r\n");
          out.write("\t\t\t\t\t<td><strong id=\"totalSize\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sumMB}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" MB / 20MB</strong></td> \r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<th scope=\"row\">글암호</th>\r\n");
          out.write("\t\t\t\t\t<td><input title=\"글 암호를 입력하세요 \" type=\"password\" name=\"pw\" id=\"pw\" class=\"short\" />\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"gobackURL\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gobackURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("\t\t\t\t\t\t<span id=\"error\" title=\"암호는 영문자,숫자,특수기호가 혼합된 8~15글자로\r\n");
          out.write("\t\t\t\t\t\t\t입력하세요.\" class=\"error\">암호는 영문자,숫자,특수기호가 혼합된 8~15글자로\r\n");
          out.write("\t\t\t\t\t\t\t입력하세요.</span></td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t</table>\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div id=\"btn\">\r\n");
          out.write("\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t<button title=\"글 수정 완료하기\" type=\"button\" id=\"btnUpdate\">완료</button>\r\n");
          out.write("\t\t\t\t\t<button title=\"취소하기 \" type=\"button\" onclick=\"javascript:history.back()\">취소</button>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</form>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/edit.jsp(539,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/edit.jsp(546,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.regDate}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/edit.jsp(548,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.regDate}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/edit.jsp(556,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.subject}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/edit.jsp(563,35) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.content}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/edit.jsp(593,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("orgFileName");
      // /WEB-INF/views/tiles1/board/edit.jsp(593,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/tiles1/board/edit.jsp(593,8) '${orgFilenameList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${orgFilenameList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/tiles1/board/edit.jsp(593,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" 번째 파일\"   id=\"file");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orgFileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<button title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" 번째 파일 삭제하기\" type=\"button\" onclick=\"delOldFile(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\">파일삭제</button>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
