/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-02-05 07:49:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles1.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 String ctxPath = request.getContextPath(); 
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\ttable, th, td, input, textarea {border: solid gray 1px;}\r\n");
      out.write("\t\r\n");
      out.write("\t#table {border-collapse: collapse;\r\n");
      out.write("\t \t\twidth: 98%;\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t#table th, #table td{padding: 5px;}\r\n");
      out.write("\t#table th{width: 10%; background-color: #DDDDDD; text-align: center;}\r\n");
      out.write("\t#table td{width: 80%;}\r\n");
      out.write("\t.long {width: 470px;}\r\n");
      out.write("\t.short {width: 120px;}\r\n");
      out.write("\t\r\n");
      out.write("\tspan#error {\r\n");
      out.write("   \tdisplay: none;\r\n");
      out.write("   \tcolor: red;\r\n");
      out.write("   }\r\n");
      out.write("\t\r\n");
      out.write("\tinput#subject {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tresize: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#btn {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\tjustify-content : center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbutton {\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t\tmargin-right: 20px;\r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar n = 1; // alert 한번만 뜨도록 설정\r\n");
      out.write("\tvar a = 0; // 조건 변수\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('textarea#content').bind({\r\n");
      out.write("\t\t\tchange: textarea_analysis,\r\n");
      out.write("\t\t\tclick: textarea_analysis,\r\n");
      out.write("\t\t\tkeydown: textarea_analysis,\r\n");
      out.write("\t\t\tmousemove: textarea_analysis,\r\n");
      out.write("\t\t\tonfocus : textarea_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input#subject').bind({\r\n");
      out.write("\t\t\tchange: subject_analysis,\r\n");
      out.write("\t\t\tclick: subject_analysis,\r\n");
      out.write("\t\t\tkeydown: subject_analysis,\r\n");
      out.write("\t\t\tmousemove: subject_analysis,\r\n");
      out.write("\t\t\tonfocus : subject_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 완료버튼\r\n");
      out.write("\t\t$(\"button#btnUpdate\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    // 글제목 유효성 검사\r\n");
      out.write("\t\t\t\t\tvar subjectVal = $(\"input#subject\").val().trim();\r\n");
      out.write("\t\t\t\t\tif(subjectVal == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"글 제목을 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    // 글내용 유효성 검사\r\n");
      out.write("\t\t\t\t\tvar contentVal = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t\t\t\tif(contentVal == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"글 내용을 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t        $(\"textarea#content\").val(contentVal);\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t\t\t// 글암호 유효성 검사\r\n");
      out.write("\t\t\t\t\tvar pwVal = $(\"input#pw\").val().trim();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(pwVal == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"글암호를 입력하세요!!\");\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar regExp = new RegExp(/^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g);\r\n");
      out.write("\t\t\t\t\t\tvar bool = regExp.test(pwVal);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(!bool) {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t// 암호가 정규표현식에 위배된 경우\r\n");
      out.write("\t\t\t\t\t\t\talert(\"암호는 영문자,숫자,특수기호가 혼합된 8~15 글자로 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t\t    $(this).focus();\r\n");
      out.write("\t\t\t\t\t\t   \t$(\"span.error\").show();\r\n");
      out.write("\t\t\t\t\t\t    return;\r\n");
      out.write("\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t// 폼(form)을 전송(submit)\r\n");
      out.write("\t\t\tvar frm = document.editFrm;\r\n");
      out.write("\t\t\tfrm.method = \"POST\";\r\n");
      out.write("\t\t\tfrm.action = \"");
      out.print( ctxPath);
      out.write("/editEnd.action\";\r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}); // end of updateBtn Function\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}); // end of $(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t   $(function(){\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t\t$('#textarea#content').bind({\r\n");
      out.write("\t\t\t\t\tchange: textarea_analysis,\r\n");
      out.write("\t\t\t\t\tclick: textarea_analysis,\r\n");
      out.write("\t\t\t\t\tkeydown: textarea_analysis,\r\n");
      out.write("\t\t\t\t\thover: textarea_analysis,\r\n");
      out.write("\t\t\t\t\tonfocus : textarea_analysis\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\tfunction textarea_analysis(event) {\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t    content = $(\"textarea#content\").val().trim();\r\n");
      out.write("\t\t\t\t    $(\"td#result\").html(\"(\"+content.length+\" / 최대 4500자)\");\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    if(content.length > 4500 ) {\r\n");
      out.write("\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t    \talert_content(1);\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        subject = $(this).val().trim();\r\n");
      out.write("\t\t\t\t        $(this).val(content.substring(0, 4500));\r\n");
      out.write("\t\t\t\t        $(\"textarea#content\").focus();\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        return;\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction subject_analysis(event) {\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\tsubject = $(\"input#subject\").val().trim();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t    if(subject.length > 90 ) {\r\n");
      out.write("\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t    \talert_content(2);\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        subject = $(this).val().trim();\r\n");
      out.write("\t\t\t\t        $(this).val(subject.substring(0, 90));\r\n");
      out.write("\t\t\t\t        $(\"input#subject\").focus();\r\n");
      out.write("\t\t\t\t        return;    \r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction alert_content(a) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(a == 1) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\talert(\"내용은 최대 4500자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\t}, 1);\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(a == 2) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\talert(\"제목은 최대 90자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\t}, 1);\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"padding-left: 5%;\">\r\n");
      out.write("\t<h1>글수정</h1>\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"editFrm\">\r\n");
      out.write("\t\t<table id=\"table\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t    <input type=\"hidden\" name=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    <c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t    <input type=\"hidden\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"subject\" id=\"subject\" class=\"long\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength='100'/>       \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"10\" cols=\"100\" style=\"height: 612px;\" name=\"content\" id=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>       \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <th>글자 수</th>\r\n");
      out.write("            <td id=\"result\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>글암호</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"pw\" id=\"pw\" class=\"short\" />\r\n");
      out.write("\t\t\t\t\t<span id=\"error\" class=\"error\">암호는 영문자,숫자,특수기호가 혼합된 8~15 글자로 입력하세요.</span>       \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div id=\"btn\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"btnUpdate\">완료</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" onclick=\"javascript:history.back()\">취소</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
