/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-02-25 06:08:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles1.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/cjh20/OneDrive/Desktop/NCS%20(1)/bowtech/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612221392006L));
    _jspx_dependants.put("jar:file:/C:/Users/cjh20/OneDrive/Desktop/NCS%20(1)/bowtech/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/cjh20/OneDrive/Desktop/NCS%20(1)/bowtech/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\tth {\r\n");
      out.write("\t\tfont-family: \"제주고딕\";\r\n");
      out.write("\t\tfont-size: 15pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput[type=text]  {\r\n");
      out.write("\t\tfont-family: \"제주고딕\";\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\tinput[type=password] {\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea {\r\n");
      out.write("\t\tfont-family: \"제주고딕\";\r\n");
      out.write("\t\tfont-size: 13pt;\r\n");
      out.write("\t\theight: 90pt;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\ttd {\r\n");
      out.write("\t\tfont-family: \"제주고딕\";\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable, th, td, input, textarea {border: solid gray 1px;}\r\n");
      out.write("\t\r\n");
      out.write("\t#table, #table2 {border-collapse: collapse;\r\n");
      out.write("\t \t\t         width: 98%;\r\n");
      out.write("\t \t\t        }\r\n");
      out.write("\t#table th, #table td{padding: 5px;}\r\n");
      out.write("\t#table th{width: 10%; background-color: #DDDDDD; text-align: center;}\r\n");
      out.write("\t#table td{width: 70%;}\r\n");
      out.write("\t.long {width: 470px;}\r\n");
      out.write("\t.short {width: 120px;}\r\n");
      out.write("\t\r\n");
      out.write("\t.move {cursor: pointer;}\r\n");
      out.write("\t.moveColor {color: #660029; font-weight: bold;}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\ta {text-decoration: none !important;}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\ttd.comment {text-align: center;}\r\n");
      out.write("\t\r\n");
      out.write("\tinput#subject {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea {\r\n");
      out.write("\t\twidth: 95%;\r\n");
      out.write("\t\tresize: none;\r\n");
      out.write("\t\theight: 80px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tdiv#btn {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\tjustify-content : center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbutton {\r\n");
      out.write("\t\tmargin-top: 0px;\r\n");
      out.write("\t\tmargin-right: 20px;\r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tpre {\r\n");
      out.write("\t\twhite-space: pre-wrap;\r\n");
      out.write("\t\tword-break: break-all;\r\n");
      out.write("\t\tfont-size: 10pt;\r\n");
      out.write("\t\tfont-family: 제주고딕; \r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#lost {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\tflex-direction: column;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#writecomment {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tbutton#btnComment {\r\n");
      out.write("\t\tmargin-top: 0;\r\n");
      out.write("\t\tmargin-bottom: 0;\r\n");
      out.write("\t\tmargin-right: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#mycontent {\r\n");
      out.write("\t\tmin-height: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbutton#btnComment {\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#displaybtn {\r\n");
      out.write("\t\twidth: 95%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\thr {\r\n");
      out.write("\t\tborder: thick;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t  button#event {\r\n");
      out.write("        float: right;\r\n");
      out.write("      }\r\n");
      out.write("      div.dropdown {\r\n");
      out.write("        float: right;\r\n");
      out.write("      }\r\n");
      out.write("      div#container {\r\n");
      out.write("        width: 97%;\r\n");
      out.write("        margin-right: 0%;\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .btn-primary {\r\n");
      out.write("        color: black;\r\n");
      out.write("        border: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      hr {\r\n");
      out.write("        border: solid 1px;\r\n");
      out.write("      }\r\n");
      out.write("      div#content {\r\n");
      out.write("        word-break:break-all;\r\n");
      out.write("        white-space:normal;\r\n");
      out.write("      } \r\n");
      out.write("      \r\n");
      out.write("      button.btn  {\r\n");
      out.write("      \tpadding: 6px 6px;\r\n");
      out.write("      \tmargin-right: 0px;\r\n");
      out.write("      \tbackground: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("       .modal-open {\r\n");
      out.write("      \toverflow: scroll;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .modal-close {\r\n");
      out.write("      \toverflow: scroll;\r\n");
      out.write("      } \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("//<![CDATA[\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\tvar n = 0; // alert 한번만 뜨도록 설정\r\n");
      out.write("\tvar a = 0; // 조건 변수\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"input#name\").bind({\r\n");
      out.write("\t\t\tinput : name_analysis,\r\n");
      out.write("\t\t\tpaste : name_analysis,\r\n");
      out.write("\t\t\tpropertychange : name_analysis\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"textarea#commentContent\").bind({\r\n");
      out.write("\t\t\tinput : content_analysis,\r\n");
      out.write("\t\t\tpaste : content_analysis,\r\n");
      out.write("\t\t\tpropertychange : content_analysis\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t // goReadComment();  // 페이징처리 안한 댓글 읽어오기 \r\n");
      out.write("\t    goViewComment(1); // 페이징처리 한 댓글 읽어오기 \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"span.move\").hover(function(){\r\n");
      out.write("\t\t\t                   $(this).addClass(\"moveColor\");\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                    ,function(){\r\n");
      out.write("\t\t                       $(this).removeClass(\"moveColor\");\r\n");
      out.write("\t\t                    });\r\n");
      out.write("\t\r\n");
      out.write("\t}); // end of $(document).ready(function(){})----------------\r\n");
      out.write("\t\r\n");
      out.write("\t// == 댓글쓰기 == //\r\n");
      out.write("\tfunction goAddWrite() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar contentVal = $(\"textarea#commentContent\").val().trim();\r\n");
      out.write("\t\tvar nameVal = $(\"input#name\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(contentVal == \"\") {\r\n");
      out.write("\t\t\talert(\"댓글 내용을 입력하세요!!\");\r\n");
      out.write("\t\t\t$(\"textarea#commentContent\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(nameVal == \"\") {\r\n");
      out.write("\t\t\talert(\"이름을 입력하세요!!\");\r\n");
      out.write("\t\t\t$(\"input#name\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 글암호 유효성 검사\r\n");
      out.write("\t\tvar pwVal = $(\"input#pw\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pwVal == \"\") {\r\n");
      out.write("\t\t\talert(\"글암호를 입력하세요!!\");\r\n");
      out.write("\t\t\t$(\"input#pw\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tvar regExp = new RegExp(/^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).*$/g);\r\n");
      out.write("\t\t\tvar bool = regExp.test(pwVal);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!bool) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 암호가 정규표현식에 위배된 경우\r\n");
      out.write("\t\t\t\talert(\"암호는 영문자,숫자,특수기호가 혼합된 8~15 글자로 입력하세요.\");\r\n");
      out.write("\t\t\t   \t$(\"input#pw\").focus();\t\t\t\t\t   \t\r\n");
      out.write("\t\t\t    return;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\tvar form_data = $(\"form[name=addWriteFrm]\").serialize();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/addComment.action\",\r\n");
      out.write("\t\t\tdata:form_data,\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(json){  // {\"n\", 1} OR {\"n\", 0}\r\n");
      out.write("\t\t\t\tvar n = json.n;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(n == 0) {\r\n");
      out.write("\t\t\t\t\talert(json.name+\"님의 포인트는 300점을 초과할 수 없으므로 댓글쓰기가 불가합니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t//\tgoReadComment();  // 페이징처리 안한 댓글 읽어오기 \r\n");
      out.write("\t\t\t\t\tgoViewComment(1); // 페이징처리 한 댓글 읽어오기 \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"textarea#commentContent\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"input#name\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"input#pw\").val(\"\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\talert(\"code: \"+request.status+\"\\n\"+\"message: \"+request.responseText+\"\\n\"+\"error: \"+error);\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t  }\r\n");
      out.write("\t\t\r\n");
      out.write("\t}// end of function goAddWrite(){}---------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// === 페이징 처리 안한 댓글 읽어오기 === // \r\n");
      out.write("\tfunction goReadComment() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/readComment.action\",\r\n");
      out.write("\t\t\tdata:{\"parentSeq\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(json){\r\n");
      out.write("\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\tif(json.length > 0) {\r\n");
      out.write("\t\t\t\t\t$.each(json, function(index, item){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar name=removeTag(item.name);\r\n");
      out.write("\t\t\t\t\t\tvar content=removeTag(item.content);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<td class='comment'>\"+item.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<td>\"+item.content+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<td class='comment'>\"+item.regDate+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td colspan='4' class='comment'>댓글이 없습니다</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* $(\"tbody#commentDisplay\").html(html); */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\talert(\"code: \"+request.status+\"\\n\"+\"message: \"+request.responseText+\"\\n\"+\"error: \"+error);\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}// end of function goReadComment(){}------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// === #127. Ajax로 불러온 댓글내용을 페이징처리 하기 === // \r\n");
      out.write("\r\n");
      out.write("\tfunction goViewComment(currentShowPageNo) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/commentList.action\",\r\n");
      out.write("\t\t\tdata:{\"parentSeq\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t\t\t\t  \"currentShowPageNo\":currentShowPageNo},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsuccess:function(json){\r\n");
      out.write("\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\tif(json.length > 0) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.each(json, function(index, item){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar name=removeTag(item.name);\r\n");
      out.write("\t\t\t\t\t\tvar content=removeTag(item.content); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtml +=\"<div id=container>\";\r\n");
      out.write("\t\t\t\t        html +=\"<hr>\";\r\n");
      out.write("\t\t\t\t        html +=\"<div>\";\r\n");
      out.write("\t\t\t\t        html +=\"<span id='name'>\"+name+\"</span>\";\r\n");
      out.write("\t\t\t\t        html +=\"<div class='dropdown'>\"\r\n");
      out.write("\t\t\t\t        html +=\"<button class='btn btn-primary dropdown-toggle' type='button' data-toggle='dropdown'>\";\r\n");
      out.write("\t\t\t\t        html +=\" <span class='caret'></span></button>\";\r\n");
      out.write("\t\t\t\t        html +=\" <ul class='dropdown-menu dropdown-menu-right'>\";\r\n");
      out.write("\t\t\t\t        html +=\" <li><a data-toggle='modal' data-target='#exampleModal\"+index+\"'>삭제</a></li>\";\r\n");
      out.write("\t\t\t\t        html +=\" </ul>\";\r\n");
      out.write("\t\t\t\t        html +=\" </div>\";\t\t\t\t          \r\n");
      out.write("\t\t\t\t        html +=\" </div>\";\r\n");
      out.write("\t\t\t\t        html +=\" <br>\";\r\n");
      out.write("\t\t\t\t        html +=\" <div id='date'>\"+item.regDate+\"</div>\";\r\n");
      out.write("\t\t\t\t        html +=\" <br>\";\r\n");
      out.write("\t\t\t\t        html +=\" <div id='content'>\";\r\n");
      out.write("\t\t\t\t        html +=content+\"</div>\";\r\n");
      out.write("\t\t\t\t        html +=\" </div>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t      html+=\"<div class='modal fade' id='exampleModal\"+index+\"' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>\";\r\n");
      out.write("\t\t\t\t      html+=\"<div class='modal-dialog' role='document'>\";\r\n");
      out.write("\t\t\t\t          html+=\"<div class='modal-content'>\";\r\n");
      out.write("\t\t\t\t            html+=\"<div class='modal-header'>\";\r\n");
      out.write("\t\t\t\t              html+=\"<h5 class='modal-title' id='exampleModalLabel'>게시물 삭제</h5>\";\r\n");
      out.write("\t\t\t\t              html+=\"<button type='button' class='close' data-dismiss='modal' aria-label='Close'>\";\r\n");
      out.write("\t\t\t\t                html+=\"<span class='plz' aria-hidden='true'>&times;</span>\";\r\n");
      out.write("\t\t\t\t              html+=\"</button>\"; \r\n");
      out.write("\t\t\t\t            html+=\"</div>\";\r\n");
      out.write("\t\t\t\t            html+=\"<form id=\"+index+\" onsubmit='return false;'>\";\r\n");
      out.write("\t\t\t\t            html+=\"<div class='modal-body'>댓글암호 : <input name='pw' type='password' onkeypress='if(event.keyCode==13) {delComment(\"+index+\",\"+item.seq+\");}'><input type='hidden' name='seq' value='\"+item.seq+\"'><input type='hidden' name='parentseq' value='\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+\"'></div>\";\r\n");
      out.write("\t\t\t\t            html+=\"<div class='modal-footer'>\";\r\n");
      out.write("\t\t\t\t              html+=\"<button type='button' class='btn btn-primary' onclick='delComment(\"+index+\",\"+item.seq+\",\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+\");'>삭제하기</button>\";\r\n");
      out.write("\t\t\t\t              html+=\"<button type='button' class='btn btn-secondary' data-dismiss='modal' aria-label='Close'>닫기</button>\"; \r\n");
      out.write("\t\t\t\t            html+=\"</div>\";\r\n");
      out.write("\t\t\t\t            html+=\"</form>\";\r\n");
      out.write("\t\t\t\t          html+=\"</div>\";\r\n");
      out.write("\t\t\t\t        html +=\"</div>\";\r\n");
      out.write("\t\t\t\t      html+=\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t/* \t\t\t\t\thtml +=\"<hr>\";\r\n");
      out.write("\t\t\t\t        html +=\"<div>\";\r\n");
      out.write("\t\t\t\t        html +=\"<span id='name'>\"+name+\"</span>\";\r\n");
      out.write("\t\t\t\t        html +=\"<button id='event' onclick=''>태그</button>\";\r\n");
      out.write("\t\t\t\t        html +=\"</div>\";\r\n");
      out.write("\t\t\t\t        html +=\"<br>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t        html+=\"<div id='date'>\"+item.regDate+\"</div>\";\r\n");
      out.write("\t\t\t\t        html+=\"<br>\";\r\n");
      out.write("\t\t\t\t        html+=\"<div id='content'>\"+content+\"</div>\";\r\n");
      out.write("\t\t\t\t        html+=\"<hr>\"; */\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("/* \t\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td colspan='4' class='comment'>댓글이 없습니다</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\"; */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("/* \t\t\t\t$(\"tbody#commentDisplay\").html(html); */\r\n");
      out.write("\t\t\t\t$(\"div#container\").html(html);\r\n");
      out.write("\t\t\t\t// 페이지바 함수 호출\r\n");
      out.write("\t\t\t\tmakeCommentPageBar(currentShowPageNo);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\talert(\"code: \"+request.status+\"\\n\"+\"message: \"+request.responseText+\"\\n\"+\"error: \"+error);\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}// end of function goReadComment(){}------------------------\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 댓글 삭제하기\r\n");
      out.write("\tfunction delComment(index,seq) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 비밀번호 index, seq\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tvar form_data = $(\"form#\"+index).serialize();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/delComment.action\",\r\n");
      out.write("\t\t\t\tdata:form_data,\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\t\tsuccess:function(json){  // {\"n\", 1} OR {\"n\", 0}\r\n");
      out.write("\t\t\t\t\tvar n = json.n;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(n == 0) {\r\n");
      out.write("\t\t\t\t\t\talert(\"비밀번호가 틀렸습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"span.plz\").click(); // 닫는건 문제가 안됨.\r\n");
      out.write("\t\t\t\t\t\t$(\"div.modal-backdrop\").remove();\r\n");
      out.write("\t\t\t\t\t\t$(\"div.modal-backdrop\").css(\"display, none\");\r\n");
      out.write("\t\t\t\t\t\t$(\"body\").css(\"overflow, scroll\");\r\n");
      out.write("\t\t\t\t\t\t// 왜안먹지\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\t\tgoViewComment(1);\r\n");
      out.write("\t\t\t\t\t\t\t}, 3);  \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\t\talert(\"code: \"+request.status+\"\\n\"+\"message: \"+request.responseText+\"\\n\"+\"error: \"+error);\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t  };\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t// ==== 댓글내용 페이지바 Ajax로 만들기 ==== //\r\n");
      out.write("\tfunction makeCommentPageBar(currentShowPageNo) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write(" \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print( request.getContextPath());
      out.write("/getCommentTotalPage.action\", \r\n");
      out.write("\t\t\tdata:{\"parentSeq\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t\t\t\t  \"sizePerPage\":\"5\"},\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(json){\r\n");
      out.write("\t\t\t//\tconsole.log(\"전체페이지수 : \" + json.totalPage);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(json.totalPage > 0) {\r\n");
      out.write("\t\t\t\t\t// 댓글이 있는 경우\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar totalPage = json.totalPage;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar pageBarHTML = \"<ul style='list-style: none;'>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar blockSize = 2;\r\n");
      out.write("\t\t\t\t\t// blockSize 는 1개 블럭(토막)당 보여지는 페이지번호의 개수 이다.\r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t      1 2 3 4 5 6 7 8 9 10  다음                   -- 1개블럭\r\n");
      out.write("\t\t\t\t\t   이전  11 12 13 14 15 16 17 18 19 20  다음   -- 1개블럭\r\n");
      out.write("\t\t\t\t\t   이전  21 22 23\r\n");
      out.write("\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar loop = 1;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t    \tloop는 1부터 증가하여 1개 블럭을 이루는 페이지번호의 개수[ 지금은 10개(== blockSize) ] 까지만 증가하는 용도이다.\r\n");
      out.write("\t\t\t\t    */\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    if(typeof currentShowPageNo == \"string\") {\r\n");
      out.write("\t\t\t\t    \tcurrentShowPageNo = Number(currentShowPageNo);\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    // *** !! 다음은 currentShowPageNo 를 얻어와서 pageNo 를 구하는 공식이다. !! *** //\r\n");
      out.write("\t\t\t\t    var pageNo = Math.floor( (currentShowPageNo - 1)/blockSize ) * blockSize + 1;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// === [맨처음][이전] 만들기 === \r\n");
      out.write("\t\t\t\t\tif(pageNo != 1) {\r\n");
      out.write("\t\t\t\t\t\tpageBarHTML += \"<li style='display:inline-block; width:60px; font-size:12pt;'><a href='javascript:goViewComment(\\\"1\\\")'>[맨처음]</a></li>\"; \r\n");
      out.write("\t\t\t\t\t\tpageBarHTML += \"<li style='display:inline-block; width:50px; font-size:11pt;'><a href='javascript:goViewComment(\\\"\"+(pageNo-1)+\"\\\")'>[이전]</a></li>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\twhile( !(loop > blockSize || pageNo > totalPage) ) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(pageNo == currentShowPageNo) {\r\n");
      out.write("\t\t\t\t\t\t\tpageBarHTML += \"<li style='display:inline-block; width:30px; font-size:11pt; border:solid 1px gray; color:red; padding:2px 4px;'>\"+pageNo+\"</li>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\tpageBarHTML += \"<li style='display:inline-block; width:30px; font-size:11pt;'><a href='javascript:goViewComment(\\\"\"+pageNo+\"\\\")'>\"+pageNo+\"</a></li>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tloop++;\r\n");
      out.write("\t\t\t\t\t\tpageNo++;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}// end of while------------------------------\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// === [다음][마지막] 만들기 ===\r\n");
      out.write("\t\t\t\t\tif( !(pageNo > totalPage) ) {\r\n");
      out.write("\t\t\t\t\t\tpageBarHTML += \"<li style='display:inline-block; width:50px; font-size:11pt;'><a href='javascript:goViewComment(\\\"\"+pageNo+\"\\\")'>[다음]</a></li>\";\r\n");
      out.write("\t\t\t\t\t\tpageBarHTML += \"<li style='display:inline-block; width:60px; font-size:11pt;'><a href='javascript:goViewComment(\\\"\"+totalPage+\"\\\")'>[마지막]</a></li>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tpageBarHTML += \"</ul>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"div#pageBar\").html(pageBarHTML);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\talert(\"code: \"+request.status+\"\\n\"+\"message: \"+request.responseText+\"\\n\"+\"error: \"+error);\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}// end of function makeCommentPageBar(currentShowPageNo){}----------\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction name_analysis(event) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar name = $(\"input#name\").val().trim();\r\n");
      out.write("\r\n");
      out.write("\t\tif (name.length > 5) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tname = $(\"input#name\").val().trim();\r\n");
      out.write("\t\t\tname_unbind();\r\n");
      out.write("\t\t\talert_content(3);\r\n");
      out.write("\t\t\t$(this).val(name.substring(0, 5));\r\n");
      out.write("\t\t\t$(\"input#name\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction name_bind() {\r\n");
      out.write("\t\tvar name = $(\"input#name\").val();\r\n");
      out.write("\t\t$(\"input#name\").val(name.substring(0, 5));\r\n");
      out.write("\t\t$('input#name').bind({\r\n");
      out.write("\t\t\tpaste : name_analysis,\r\n");
      out.write("\t\t\tinput : name_analysis,\r\n");
      out.write("\t\t\tpropertychange : name_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction name_unbind() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"input#name\").unbind(\"input\");\r\n");
      out.write("\t\t$(\"input#name\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"input#name\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction content_analysis(event) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar content = $(\"textarea#commentContent\").val().trim();\r\n");
      out.write("\t\t$(\"strong#result\").html(content.length);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (content.length > 300) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"strong#result\").html(\"300\");\r\n");
      out.write("\t\t\tcontent = $(\"textarea#commentContent\").val();\r\n");
      out.write("\t\t\tcontent_unbind();\r\n");
      out.write("\t\t\talert_content(2);\r\n");
      out.write("\t\t\t$(\"textarea#commentContent\").val(content.substring(0, 300));\r\n");
      out.write("\t\t\t$(\"textarea#commentContent\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction content_bind() {\r\n");
      out.write("\t\tvar content = $(\"textarea#commentContent\").val();\r\n");
      out.write("\t\t$(\"textarea#commentContent\").val(content.substring(0, 300) );\r\n");
      out.write("\t\t$('textarea#commentContent').bind({\r\n");
      out.write("\t\t\tpaste : content_analysis,\r\n");
      out.write("\t\t\tinput : content_analysis,\r\n");
      out.write("\t\t\tpropertychange : content_analysis\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction content_unbind() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"textarea#commentContent\").unbind(\"input\");\r\n");
      out.write("\t\t$(\"textarea#commentContent\").unbind(\"paste\");\r\n");
      out.write("\t\t$(\"textarea#commentContent\").unbind(\"propertychange\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction alert_content(a) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 함수 실행 깃발\r\n");
      out.write("\r\n");
      out.write("\t\tif (n == 1) {\r\n");
      out.write("\t\t\tn = 0;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//textarea_bind();\r\n");
      out.write("\t\t\tcontent_bind();\r\n");
      out.write("\t\t\tname_bind();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 제목\r\n");
      out.write("\t\tif (a == 2) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"댓글은 최대 300자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\talert_content(2);\t\t\r\n");
      out.write("\t\t\t\t}, 0.01);\r\n");
      out.write("\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t\t// 이름\r\n");
      out.write("\t\tif (a == 3) {\r\n");
      out.write("\t\t\talert(\"이름은 최대 5자 까지 입력 가능합니다.\");\r\n");
      out.write("\t\t\tn = 1;\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\talert_content(3);\t\t\r\n");
      out.write("\t\t\t\t}, 0.01);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\r\n");
      out.write("\t}; // end of alert 함수\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction removeTag(text) {\r\n");
      out.write("\t\ttext = text.replace(/<br\\/>/ig, \"\\n\");\r\n");
      out.write("\t\ttext = text.replace(/<(\\/)?([a-zA-Z]*)(\\s[a-zA-Z]*=[^>]*)?(\\s)*(\\/)?>/ig, \"\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn text;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("//]]>\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"padding-left: 5%;\">\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/views/tiles1/board/view.jsp(674,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" \r\n");
            out.write("\t\t<table id=\"table\">\r\n");
            out.write("\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>작성자</th>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write(" </td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>제목</th>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>내용</th>\r\n");
            out.write("\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t <pre>");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write("</pre>\r\n");
            out.write("\t\t\t\t ");
            out.write("\r\n");
            out.write("\t\t\t\t</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>조회수</th>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.readCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>작성일</th>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.regDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>첨부파일</th>\r\n");
            out.write("\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f2_reused = false;
            try {
              _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
              // /WEB-INF/views/tiles1/board/view.jsp(713,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
              if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t<a href=\"");
                  out.print( request.getContextPath());
                  out.write("/download.action?seq=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write('"');
                  out.write('>');
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.orgFilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</a> \r\n");
                  out.write("\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
              _jspx_th_c_005fif_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\t\t\t\t</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th>파일크기(bytes)</th>\r\n");
            out.write("\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t</table>\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t<br/>\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"btn\">\r\n");
      out.write("\t\t \t  \r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t                        \r\n");
      out.write("\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f8_reused = false;
      try {
        _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f8.setParent(null);
        // /WEB-INF/views/tiles1/board/view.jsp(764,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
        if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<button type=\"button\" onclick=\"javascript:location.href='");
            out.print( request.getContextPath());
            out.write("/list.action'\">목록으로</button>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
        _jspx_th_c_005fif_005f8_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f9_reused = false;
      try {
        _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f9.setParent(null);
        // /WEB-INF/views/tiles1/board/view.jsp(768,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
        if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<button type=\"button\" onclick=\"javascript:location.href='");
            out.print( request.getContextPath());
            out.write("/edit.action?seq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&gobackURL=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gobackURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\">수정</button>\r\n");
            out.write("\t\t<button type=\"button\" onclick=\"javascript:location.href='");
            out.print( request.getContextPath());
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gobackURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\">목록으로</button>\r\n");
            out.write("\t\t<button type=\"button\" onclick=\"javascript:location.href='");
            out.print( request.getContextPath());
            out.write("/del.action?seq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\">삭제</button>\r\n");
            out.write("\t\t<button type=\"button\" onclick=\"javascript:location.href='");
            out.print( request.getContextPath());
            out.write("/add.action?fk_seq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&groupno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.groupno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&depthno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.depthno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\">답변글쓰기</button>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
        _jspx_th_c_005fif_005f9_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
      }
      out.write("\t\t                        \t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f10_reused = false;
      try {
        _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f10.setParent(null);
        // /WEB-INF/views/tiles1/board/view.jsp(777,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser.gradelevel == 10}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
        if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    \t<button type=\"button\" onclick=\"javascript:location.href='");
            out.print( request.getContextPath());
            out.write("/add.action?fk_seq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&groupno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.groupno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&depthno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.depthno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\">답변글쓰기</button>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
        _jspx_th_c_005fif_005f10_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f10_reused);
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" \t\r\n");
      out.write("\t<!-- === #83. 댓글쓰기 폼 추가 === -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<div id =\"writeBorder\">\t\r\n");
      out.write("\t<form name=\"addWriteFrm\">\r\n");
      out.write("\t\t   <h3 style=\"margin-top: 50px;\">댓글쓰기 및 보기</h3>\r\n");
      out.write("          <div style=\"margin-right: 5%;\">\r\n");
      out.write("             <strong>작성자 : </strong>\r\n");
      out.write("              <input type=\"text\" id=\"name\" name=\"name\">\r\n");
      out.write("              <input type=\"hidden\" name=\"fk_userid\" value=\"leess\" />\r\n");
      out.write("              <input type=\"hidden\" name=\"parentSeq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("              <div style=\"display: inline-block; float: right; \">\r\n");
      out.write("            \t<strong>암호 : </strong>\r\n");
      out.write("  \t\t\t\t<input type=\"password\" id=\"pw\" name=\"comment_pw\">\t  \r\n");
      out.write("              </div>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("            <strong>댓글내용</strong>\r\n");
      out.write("            <div>\r\n");
      out.write("              <textarea id=\"commentContent\" name=\"content\" rows=\"3\" cols=\"30\"></textarea>    \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"displaybtn\">\r\n");
      out.write("            <strong id=\"result\"> 0 </strong> / <span> 300</span>\r\n");
      out.write("               <button type=\"button\" id=\"btnComment\" type=\"button\" onclick=\"goAddWrite()\">\r\n");
      out.write("                  <span>등록</span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("  </form>\r\n");
      out.write("</div>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- ===== #94. 댓글 내용 보여주기 ===== -->\r\n");
      out.write("<!-- \t<table id=\"table2\" style=\"margin-top: 2%; margin-bottom: 3%;\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th style=\"width: 10%; text-align: center;\">작성자</th>\r\n");
      out.write("\t\t\t<th style=\"width: 60%; text-align: center;\">내용</th>\r\n");
      out.write("\t\t\t<th style=\"text-align: center;\">작성일자</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody id=\"commentDisplay\"></tbody>\r\n");
      out.write("\t</table> -->\r\n");
      out.write("\t\r\n");
      out.write("\t  <div id=\"container\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("\t<!-- ==== #136. 댓글 페이지바 ==== -->\r\n");
      out.write("\t<div id=\"pageBar\" style=\"border:solid 0px gray; width: 90%; margin: 10px auto; text-align: center;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"exampleModalLabel\">게시물 삭제</h5>\r\n");
      out.write("            <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("              <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("            </button> \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"modal-body\">댓글암호 : <input type=\"password\"><input type=\"hidden\" value=\"\"></div>\r\n");
      out.write("          <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" id=\"btnDelete\" onclick=\"delComment();\" class=\"btn btn-primary\">삭제하기</button>\r\n");
      out.write("            <button type=\"button\" onclick=\"javascript:history.back()\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소하기</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/tiles1/board/view.jsp(669,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<h1>글내용보기</h1>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(682,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(686,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.subject}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(691,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.content}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(717,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.orgFilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(724,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.fileSize}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/tiles1/board/view.jsp(724,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(731,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("gobackURL2");
      // /WEB-INF/views/tiles1/board/view.jsp(731,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/tiles1/board/view.jsp(731,2) '${ fn:replace(gobackURL, \"&\" ,\" \") }'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_0),"${ fn:replace(gobackURL, \"&\" ,\" \") }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/tiles1/board/view.jsp(732,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t");
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/views/tiles1/board/view.jsp(733,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.previoussubject != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t \t<div style=\"margin-bottom: 1%;\">이전글&nbsp;:&nbsp;<span class=\"move\" onclick=\"javascript:location.href='view.action?seq=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.previousseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&gobackURL=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gobackURL2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write('"');
          out.write('>');
          if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fif_005f5, _jspx_page_context))
            return true;
          out.write("</span></div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
      // /WEB-INF/views/tiles1/board/view.jsp(734,172) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.previoussubject}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/views/tiles1/board/view.jsp(736,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.nextseq != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t \t<div style=\"margin-bottom: 1%;\">다음글&nbsp;:&nbsp;<span class=\"move\" onclick=\"javascript:location.href='view.action?seq=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.nextseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&gobackURL=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gobackURL2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('\'');
          out.write('"');
          out.write('>');
          if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fif_005f6, _jspx_page_context))
            return true;
          out.write("</span></div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f6);
      // /WEB-INF/views/tiles1/board/view.jsp(737,168) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardvo.nextsubject}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/tiles1/board/view.jsp(746,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty boardvo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"lost\">\r\n");
          out.write("\t\t<h2>요청하신 페이지를 찾을 수 없습니다.</h2>\r\n");
          out.write("\t\t<h5>입력한 주소가 잘못되었거나, 사용이 일시 중단되어 요청하신 페이지를 찾을 수 없습니다.</h5>\r\n");
          out.write("\t\t<h5>서비스 이용에 불편을 드려 죄송합니다.</h5>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
